version: '3'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile_test
    #command: go test -v
    depends_on:
      - myfirstgoproject
  myfirstgoproject:
    image: lucaiovio/myfirstgoproject:latest
    
